"""crear tablas de nutricion

Revision ID: 56c9d3123667
Revises: 23eca8e50819
Create Date: 2026-05-16 02:55:49.334278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c9d3123667'
down_revision: Union[str, Sequence[str], None] = '23eca8e50819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_comida', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('calorias_estimadas', sa.Integer(), nullable=True),
    sa.Column('foto_path', sa.String(length=500), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=True),
    sa.Column('metodo_validacion', sa.String(length=50), nullable=True),
    sa.Column('detalle_validacion', sa.Text(), nullable=True),
    sa.Column('puntos_otorgados', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_logs_fecha'), 'meal_logs', ['fecha'], unique=False)
    op.create_index(op.f('ix_meal_logs_id'), 'meal_logs', ['id'], unique=False)
    op.create_index(op.f('ix_meal_logs_user_id'), 'meal_logs', ['user_id'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('vasos', sa.Integer(), nullable=True),
    sa.Column('puntos_otorgados', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_logs_fecha'), 'water_logs', ['fecha'], unique=False)
    op.create_index(op.f('ix_water_logs_id'), 'water_logs', ['id'], unique=False)
    op.create_index(op.f('ix_water_logs_user_id'), 'water_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_logs_user_id'), table_name='water_logs')
    op.drop_index(op.f('ix_water_logs_id'), table_name='water_logs')
    op.drop_index(op.f('ix_water_logs_fecha'), table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index(op.f('ix_meal_logs_user_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_fecha'), table_name='meal_logs')
    op.drop_table('meal_logs')
    # ### end Alembic commands ###
