"""crear tablas de coaching

Revision ID: 7f8574cd6c6d
Revises: ba83a3648da1
Create Date: 2026-05-16 02:02:45.380328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8574cd6c6d'
down_revision: Union[str, Sequence[str], None] = 'ba83a3648da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('especialidad', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.String(length=10), nullable=True),
    sa.Column('usos', sa.Integer(), nullable=True),
    sa.Column('max_usos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_invite_codes_coach_id'), 'coach_invite_codes', ['coach_id'], unique=False)
    op.create_index(op.f('ix_coach_invite_codes_codigo'), 'coach_invite_codes', ['codigo'], unique=True)
    op.create_index(op.f('ix_coach_invite_codes_id'), 'coach_invite_codes', ['id'], unique=False)
    op.create_table('coach_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('especialidad', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_vinculacion', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_player_coach_id'), 'coach_player', ['coach_id'], unique=False)
    op.create_index(op.f('ix_coach_player_id'), 'coach_player', ['id'], unique=False)
    op.create_index(op.f('ix_coach_player_player_id'), 'coach_player', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_player_player_id'), table_name='coach_player')
    op.drop_index(op.f('ix_coach_player_id'), table_name='coach_player')
    op.drop_index(op.f('ix_coach_player_coach_id'), table_name='coach_player')
    op.drop_table('coach_player')
    op.drop_index(op.f('ix_coach_invite_codes_id'), table_name='coach_invite_codes')
    op.drop_index(op.f('ix_coach_invite_codes_codigo'), table_name='coach_invite_codes')
    op.drop_index(op.f('ix_coach_invite_codes_coach_id'), table_name='coach_invite_codes')
    op.drop_table('coach_invite_codes')
    # ### end Alembic commands ###
