"""agregar rol de usuario

Revision ID: b3215bd3f1b2
Revises: d25f47ae1f06
Create Date: 2026-05-14 16:15:51.304473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3215bd3f1b2'
down_revision: Union[str, Sequence[str], None] = 'd25f47ae1f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Agregar columna permitiendo NULL temporalmente
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    
    # 2. Llenar usuarios existentes con valor por defecto
    op.execute("UPDATE users SET role = 'jugador' WHERE role IS NULL")
    
    # 3. Ahora sí, hacer la columna NOT NULL
    op.alter_column('users', 'role', nullable=False)
    
    # 4. Crear el índice
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
