"""crear tabla pain_reports

Revision ID: ba83a3648da1
Revises: d901521347fc
Create Date: 2026-05-16 01:52:04.786109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba83a3648da1'
down_revision: Union[str, Sequence[str], None] = 'd901521347fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pain_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('zona_cuerpo', sa.String(length=50), nullable=False),
    sa.Column('lado', sa.String(length=20), nullable=True),
    sa.Column('intensidad', sa.Float(), nullable=False),
    sa.Column('tipo_molestia', sa.String(length=30), nullable=False),
    sa.Column('momento_dolor', sa.String(length=30), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('requiere_atencion', sa.Boolean(), nullable=True),
    sa.Column('resuelto', sa.Boolean(), nullable=True),
    sa.Column('fecha_resolucion', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pain_reports_fecha'), 'pain_reports', ['fecha'], unique=False)
    op.create_index(op.f('ix_pain_reports_id'), 'pain_reports', ['id'], unique=False)
    op.create_index(op.f('ix_pain_reports_user_id'), 'pain_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pain_reports_user_id'), table_name='pain_reports')
    op.drop_index(op.f('ix_pain_reports_id'), table_name='pain_reports')
    op.drop_index(op.f('ix_pain_reports_fecha'), table_name='pain_reports')
    op.drop_table('pain_reports')
    # ### end Alembic commands ###
