"""crear tablas de ejercicios y rutinas

Revision ID: d25f47ae1f06
Revises: aea68e3fc7b0
Create Date: 2026-05-14 15:57:21.251293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25f47ae1f06'
down_revision: Union[str, Sequence[str], None] = 'aea68e3fc7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('deporte', sa.String(length=50), nullable=True),
    sa.Column('objetivo', sa.String(length=50), nullable=True),
    sa.Column('nivel_dificultad', sa.String(length=20), nullable=True),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('descanso_segundos', sa.Integer(), nullable=True),
    sa.Column('points_value', sa.Integer(), nullable=True),
    sa.Column('requiere_equipamiento', sa.Boolean(), nullable=True),
    sa.Column('equipamiento_necesario', sa.String(length=200), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_category'), 'exercises', ['category'], unique=False)
    op.create_index(op.f('ix_exercises_deporte'), 'exercises', ['deporte'], unique=False)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_objetivo'), 'exercises', ['objetivo'], unique=False)
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_estimada_minutos', sa.Integer(), nullable=True),
    sa.Column('total_puntos_disponibles', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_fecha'), 'routines', ['fecha'], unique=False)
    op.create_index(op.f('ix_routines_id'), 'routines', ['id'], unique=False)
    op.create_index(op.f('ix_routines_user_id'), 'routines', ['user_id'], unique=False)
    op.create_table('exercise_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_completions_completed_at'), 'exercise_completions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_exercise_completions_id'), 'exercise_completions', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_completions_user_id'), 'exercise_completions', ['user_id'], unique=False)
    op.create_table('routine_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_exercises_id'), 'routine_exercises', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routine_exercises_id'), table_name='routine_exercises')
    op.drop_table('routine_exercises')
    op.drop_index(op.f('ix_exercise_completions_user_id'), table_name='exercise_completions')
    op.drop_index(op.f('ix_exercise_completions_id'), table_name='exercise_completions')
    op.drop_index(op.f('ix_exercise_completions_completed_at'), table_name='exercise_completions')
    op.drop_table('exercise_completions')
    op.drop_index(op.f('ix_routines_user_id'), table_name='routines')
    op.drop_index(op.f('ix_routines_id'), table_name='routines')
    op.drop_index(op.f('ix_routines_fecha'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_exercises_objetivo'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_deporte'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_category'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
