"""crear tabla session_loads

Revision ID: d901521347fc
Revises: b3215bd3f1b2
Create Date: 2026-05-14 21:01:12.035837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd901521347fc'
down_revision: Union[str, Sequence[str], None] = 'b3215bd3f1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('carga_interna', sa.Float(), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_loads_fecha'), 'session_loads', ['fecha'], unique=False)
    op.create_index(op.f('ix_session_loads_id'), 'session_loads', ['id'], unique=False)
    op.create_index(op.f('ix_session_loads_user_id'), 'session_loads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_loads_user_id'), table_name='session_loads')
    op.drop_index(op.f('ix_session_loads_id'), table_name='session_loads')
    op.drop_index(op.f('ix_session_loads_fecha'), table_name='session_loads')
    op.drop_table('session_loads')
    # ### end Alembic commands ###
